blueprint:
  name: Outdoor Light w/ Interval and Motion
  description: Turn on outdoor lights after sunset within interval and outside interval on motion detected
  source_url: https://raw.githubusercontent.com/KristianOellegaard/homeassistant-blueprints/master/outdoor_light_with_interval_and_motion.yaml
  domain: automation
  input:
    wait_until_off:
      name: "Minutes from motion stops until the light turn off"
      default:
        hours: 0
        minutes: 3
        seconds: 0
      selector:
        duration:
    motion_entity:
      name: Motion Sensor
      selector:
        entity:
          filter:
            domain: binary_sensor
            device_class: motion
          multiple: false
    light_target:
      name: Lights
      selector:
        target:
          entity:
            domain: light
    on_schedule:
      name: Lights On Schedule
      selector:
        entity:
          multiple: false
          filter:
            domain: schedule
mode: restart
max_exceeded: silent
trigger:
  - platform: sun
    event: sunset
  - platform: state
    entity_id: !input on_schedule
  - platform: sun
    event: sunrise
    offset: 0
  - platform: state
    id: motion
    to: "on"
    entity_id:
      - !input motion_entity
condition: []
action:
  - if:
      - condition: sun
        before: sunrise
        after: sunset
      - condition: or
        conditions:
          - condition: state
            entity_id: !input on_schedule
            state: "on"
          - condition: state
            entity_id: !input motion_entity
            state: "on"
    then:
      - service: light.turn_on
        data:
          brightness_pct: 100
        target: !input light_target
      - if:
          - condition: trigger
            id:
              - motion
          - condition: state
            entity_id: !input on_schedule
            state: "off"
        then:
          - delay:
              !input wait_until_off
          - service: light.turn_off
            target: !input light_target
            data: {}
    
    else:
      - service: light.turn_off
        data: {}
        target: !input light_target
